name: Build (multi-arch) & Push to DockerHub

on:
  workflow_dispatch:
    inputs:
      imagename:
        description: 'Name of image'
        required: true
        default: 'rakheshster/kea-knot'
      version:
        description: 'Version'
        required: true

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      -
        name: Docker Buildx (build)
        run: |
          IMAGENAME=${{ inputs.imagename }}
          PLATFORMS="linux/amd64,linux/386,linux/arm/v7,linux/arm/v6"
          VERSION=${{ inputs.version }}

          docker buildx build --platform $PLATFORMS --output "type=image,push=false" . --tag ${IMAGENAME}-${VERSION}
      -
        name: Login to Docker Hub
        if: success() && github.event_name != 'pull_request'
        uses: crazy-max/ghaction-docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Docker Buildx (push)
        if: success() && github.event_name != 'pull_request'
        run: |
          IMAGENAME=${{ inputs.imagename }}
          PLATFORMS="linux/amd64,linux/386,linux/arm/v7,linux/arm/v6"
          VERSION=${{ inputs.version }}

          docker buildx build --platform $PLATFORMS --output "type=image,push=true" . --tag ${IMAGENAME}-${VERSION}
      -
        name: Inspect image
        if: always() && github.event_name != 'pull_request'
        run: |
          IMAGENAME=${{ inputs.imagename }}
          PLATFORMS="linux/amd64,linux/386,linux/arm/v7,linux/arm/v6"
          VERSION=${{ inputs.version }}

          docker buildx imagetools inspect ${IMAGENAME}-${VERSION}
