name: Build (multi-arch) & Push to DockerHub

on:
  workflow_dispatch:
    inputs:
      imagename:
        description: 'Name of image'
        required: true
        default: 'rakheshster/kea-knot'
      version:
        description: 'Version'
        required: true

jobs:
  buildx:
    runs-on: ubuntu-latest
    env: 
      IMAGENAME=${{ inputs.imagename }}
      PLATFORMS="linux/amd64,linux/386,linux/arm/v7,linux/arm/v6"
      VERSION=${{ inputs.version }}
      DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}  

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Docker Buildx (build)
        run: |
          docker buildx build --platform $PLATFORMS --output "type=image,push=false" . --tag ${IMAGENAME}-${VERSION}
      -
        name: Login to Docker Hub
        if: success() && github.event_name != 'pull_request'
        uses: crazy-max/ghaction-docker-login@v1
        with:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
      -
        name: Docker Buildx (push)
        if: success() && github.event_name != 'pull_request'
        run: |
          docker buildx build --platform $PLATFORMS --output "type=image,push=true" . --tag ${IMAGENAME}-${VERSION}
      -
        name: Inspect image
        if: always() && github.event_name != 'pull_request'
        run: |
          docker buildx imagetools inspect ${IMAGENAME}-${VERSION}
